version: '3.8'

services:
  app:
    networks:
      - matcha

  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    environment:
      - SQLD_NODE=primary
    volumes:
      - ./data/libsql:/var/lib/sqlddb
    networks:
      - matcha

networks:
  matcha:
